Import('env')
env.Program('host', source=['host.cpp','#util/Util.cpp'], 
            CCFLAGS=' -O2  -g3 -std=c++0x', 
           CPPPATH = ['/opt/AMDAPP/include/','#util'],
           LIBS=['OpenCL'],LIBPATH='/opt/AMDAPP/lib/x86_64')
#env.Program('host', source=['host.cpp','#util/Util.cpp'], 
#            CCFLAGS=' -O2  -g3 -std=c++0x', 
#          CPPPATH = ['/opt/intel/opencl-1.2-3.1.1.11385/include/','#util'],
#           LIBS=['OpenCL'],LIBPATH='/opt/intel/opencl-1.2-3.1.1.11385/lib64')