Import('env')
env.Program('host', source=['host.cpp',env2.Object('#util/Util.cpp')], 
            CCFLAGS=' -O2  -std=c++0x', 
           CPPPATH = ['/opt/intel/opencl/include/','#util'],
           LIBS=['OpenCL'],LIBPATH='/opt/intel/opencl/lib64')
