Import('env')
env.Program('host', source=['host.cpp','#util/Util.cpp'], 
            CCFLAGS=' -O2  -g3 -std=c++0x', 
           CPPPATH = ['/opt/AMDAPP/include/','#util'],
           LIBS=['OpenCL'],LIBPATH='/opt/AMDAPP/lib/x86_64')

env.Program('host2', source=['host2.cpp','#util/Util.cpp'], 
            CCFLAGS=' -O2  -g3 -std=c++0x', 
           CPPPATH = ['/opt/AMDAPP/include/','#util'],
           LIBS=['OpenCL'],LIBPATH='/opt/AMDAPP/lib/x86_64')
env.Program('host3', source=['host3.cpp','#util/Util.cpp'], 
            CCFLAGS=' -O2  -g3 -std=c++0x', 
           CPPPATH = ['/opt/AMDAPP/include/','#util'],
           LIBS=['OpenCL'],LIBPATH='/opt/AMDAPP/lib/x86_64')
