env  =  Environment(CC = 'gcc-4.8', CXX = 'g++-4.8')

cpu.Append(CCFLAGS=' -O2  -march=native -mtune=native -flax-vector-conversions  -std=c++0x')
env.SConscript(dirs=['adpcm', 'adpcm_opencl','motion','motion_opencl','aes','aes_opencl',
	                   'blowfish', 'blowfish_opencl',
                     'dfadd' , 'dfadd_opencl', 'dfsin', 'dfsin_opencl', 'dfmul', 
                     'dfmul_opencl', 'gsm', 'gsm_opencl', 'sha', 'sha_opencl',
                     'dfdiv', 'dfdiv_opencl','jpeg', 'jpeg_opencl',
                      'sha','sha_opencl', 'hash_probe'], exports='env')
                

 
 	
